### ISSUE TITLE
Include example queries

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg-neo4j#21]

**Comment by Masrepus** [comment]
The evaluation chapter of my thesis has some cryptography related queries and step by step explanations how they are constructed. Konrad should have it somewhere I think

**Comment by oxisto** [comment]
Let's open source your thesis then :)

**Comment by Masrepus** [comment]
That won't be possible unfortunately, because I had it published by GRIN and they don't allow further publishing. But we can still use the queries separately, if you think they could help
